[package]
name = "scan_fmt"
version = "0.1.3"
authors = ["wlentz"]
description = "A simple scanf()-like input for Rust"
repository = "https://github.com/wlentz/scan_fmt"
license = "MIT"
readme = "README.md"

[dependencies]
regex = "1.0.0"

[lib]
name = "scan_fmt"
path = "src/lib.rs"
